import { THEME } from './current';

const cyber = {
  missions: 'Missões',
  missionsSingular: 'Missão',
  adminMenu: 'Menu Administrativo',
  loading: 'Carregando recursos...',

  backToMissions: 'Voltar para Missões',
  seeMissions: 'Ver Missões',
  seeMyMissions: 'Ver Minhas Missões',
  goToMissions: 'Ir para Missões',
  yourMissions: 'Suas Missões',
  editMissions: 'Editar Missões',
  manageMissionsUpper: 'GERENCIAR MISSÕES',
  missionsCompletedUpper: 'MISSÕES CONCLUÍDAS',
  fulfillMissionsUpper: 'CUMPRIR MISSÕES',
  missionsFrozen: 'Missões congeladas por enquanto',
  missionsFinished: 'Missões encerradas',

  missionDone: 'Missão cumprida',
  missionDoneBang: 'Missão cumprida!',
  missionDoneUpper: 'MISSÃO CUMPRIDA',
  missionNotFound: 'Missão não encontrada',
  unknownMission: 'Missão Desconhecida',

  missionTitleLabel: 'Título da Missão',
  missionTypeLabel: 'Tipo da Missão',
  missionLinksLabel: 'Links da Missão (Opcional, até 3)',

  loadingMissionUpper: 'CARREGANDO MISSÃO...',
  loadingMissionsUpper: 'CARREGANDO MISSÕES...',
  noGlobalMissionsUpper: 'NENHUMA MISSÃO GLOBAL. CRIE UMA MISSÃO SEM CAMPANHA PARA COMEÇAR.',
  noCampaignMissionsUpper: 'NENHUMA MISSÃO NESTA CAMPANHA. CLIQUE EM "CRIAR MISSÃO" PARA INICIAR.',

  globalMissionsTab: 'Missões Globais',
  globalMissionsHintUpper: 'MISSÕES SEM CAMPANHA VINCULADA',
  globalMissionsNotDirect: 'Missões globais (modelo) não são completadas diretamente',
  whoCompletedMission: 'Participantes que já concluíram esta missão',

  createMission: 'Criar Missão',
  newGlobalMission: 'Nova Missão Global',
  editMission: 'Editar Missão',
  globalMissionSuffix: 'Missão Global',
  campaignMissionSuffix: 'Missão na Campanha',
  saveMission: 'Salvar Missão',
  finishAndCreateMission: 'Concluir e Criar Missão',
  assignMissionToCampaign: 'Atribuir Missão a uma Campanha',
  confirmDeleteMission: 'Confirmar Exclusão de Missão',

  missionGoneProse: 'Esta missão não existe mais ou foi removida.',
  missionFormSubtitle: 'Configuração da missão do participante',
  missionWillBeGlobalProse: 'Esta missão será criada sem campanha vinculada (global).',
  activateMissionNow: 'Ativar missão imediatamente',
  activeOnlyWhenLinked: 'Ativo/inativo só se aplica quando a missão está vinculada a uma campanha',
  missionsPageSubtitle: 'Criação e configuração das missões dos participantes',
  selectCampaignToManage: 'Selecione a campanha para visualizar e gerenciar suas missões',
  globalMissionsProse: 'Estas missões estão prontas mas não estão associadas a nenhuma campanha ativa.',
  confirmDeleteProse: 'Tem certeza de que deseja excluir a missão',
  campaignWipeProse: 'Esta operação apagará todos os dados, missões, prêmios e cupons associados a esta campanha.',
  reopensMissionsProse: 'participante E reabre as missões, permitindo ganhar mais cupons',
  reopenMissionsSoonProse: '"Ativa" pra sinalizar que a próxima rodada vem em breve e reabrir as missões, pra quem quiser',

  referralHintProse: 'Passe esse código pra um amigo cumprir a missão "Indique um Amigo". Ele ganha cupons na hora; os seus caem quando ele concluir a primeira missão dele.',
  receivedCodeProse: 'Recebeu um código de amigo? Vá até a missão',
  completeMoreProse: 'Quer ganhar ainda mais cupons e aumentar suas chances de ganhar? Complete as missões disponíveis.',
  campaignFallbackProse: 'Cumpra missões, junte cupons e concorra a prêmios incríveis!',
  remainingMissionsSubtitle: 'Complete as missões restantes para ganhar mais cupons!',

  sysReady: '[SYS_READY]',
  sysWaiting: '[SYS_WAITING]',

  heroParagraph:
    'Participe das missões, acumule cupons e aumente suas chances de ganhar nos sorteios ao vivo. Cada missão concluída rende novos cupons para você aumentar suas chances.',
  ctaRegister: 'Criar Personagem',
  ctaLogin: 'Continuar História',

  loginTitle: 'CONTINUAR HISTÓRIA',
  loginSubtitle: 'CONTINUE DE ONDE PAROU',
  loginSubmit: 'RETORNAR AO JOGO',
  loginOverlay: 'AUTENTICANDO CREDENCIAIS...',
  loginNoAccount: 'SEM SAVE?',
  loginCreateLink: 'CRIAR NOVO >',

  registerTitle: 'CRIAR SAVEPOINT',
  registerSubtitle: 'CRIE SEU AVATAR E INICIE A JORNADA',
  registerSubmit: 'CRIAR PERSONAGEM',
  registerOverlay: 'INICIALIZANDO REGISTRO...',
  registerHasAccount: 'Já possui save?',

  landingCampaigns: '⚡ CAMPANHAS ATIVAS',
  landingRanking: '🏆 RANKING DE CUPONS',
  landingHowItWorks: '💡 COMO FUNCIONA',
  landingFaq: '❓ PERGUNTAS FREQUENTES',

  step1Title: 'CRIAR CONTA',
  step2Title: 'CUMPRIR MISSÕES',
  step1Desc: 'Crie sua identidade digital com nome, telefone e PIN de 4 dígitos. O cadastro pede o código exibido na tela do nosso estande.',
  step2Desc: 'Complete as missões disponíveis na campanha. Algumas podem exigir o envio de um comprovante, outras podem envolver questionários, formulários ou ações automáticas.',
  step3Title: 'COLETE CUPONS',
  step3Desc: 'Cada missão concluída adiciona novos cupons à sua conta. Quanto mais cupons você tiver, maiores serão suas chances no sorteio.',
  step4Title: 'ASSISTIR AO SORTEIO AO VIVO',
  step4Desc: 'No horário marcado, acompanhe o sorteio ao vivo diretamente pela plataforma e descubra os vencedores em tempo real.',

  faq1Q: 'Como funciona o sistema de cupons do sorteio?',
  faq1A: 'Cada missão concluída concede uma quantidade de cupons. No momento do sorteio, cada cupom representa uma chance adicional de ser sorteado.',
  faq2Q: 'Que tipos de missões/tarefas existem?',
  faq2A: 'As missões variam conforme a campanha. Elas podem incluir envio de comprovantes, quizzes, formulários de feedback ou outras atividades definidas pelos organizadores.',
  faqStandQ: 'Preciso estar no evento para me cadastrar?',
  faqStandA: 'Sim. O cadastro pede um código de 4 dígitos que fica exposto na tela do nosso estande e muda de tempos em tempos. Sem ele não é possível criar conta, e é assim que garantimos que só quem está presente participa do sorteio.',
  faqReferralQ: 'Como funciona o código de amigo?',
  faqReferralA: 'Cada participante tem um código de 6 dígitos. Quem usa o código de um amigo ganha cupons na hora. Já o dono do código só recebe os cupons dele quando a pessoa indicada concluir a primeira missão — não basta digitar o código. Cada código vale para até 10 pessoas.',
  faq3A: 'Caso uma missão exija um comprovante, siga as instruções exibidas na descrição da missão e envie a imagem solicitada. Após o envio, a missão será validada conforme as regras da campanha.',

  dashboardLoading: 'Carregando sua aventura...',
  noCampaignProse:
    'Ainda não temos uma campanha ativa. Fique de olho — assim que uma nova aventura começar, ela aparece bem aqui.',
  prizesTitle: 'Prêmios em Jogo',
};

const padrao: typeof cyber = {
  missions: 'Desafios',
  missionsSingular: 'Desafio',
  adminMenu: 'Administração',
  loading: 'Carregando',

  backToMissions: 'Voltar para Desafios',
  seeMissions: 'Ver Desafios',
  seeMyMissions: 'Ver Meus Desafios',
  goToMissions: 'Ir para Desafios',
  yourMissions: 'Seus Desafios',
  editMissions: 'Editar Desafios',
  manageMissionsUpper: 'GERENCIAR DESAFIOS',
  missionsCompletedUpper: 'DESAFIOS CONCLUÍDOS',
  fulfillMissionsUpper: 'CUMPRIR DESAFIOS',
  missionsFrozen: 'Desafios congelados por enquanto',
  missionsFinished: 'Desafios encerrados',

  missionDone: 'Desafio cumprido',
  missionDoneBang: 'Desafio cumprido!',
  missionDoneUpper: 'DESAFIO CUMPRIDO',
  missionNotFound: 'Desafio não encontrado',
  unknownMission: 'Desafio Desconhecido',

  missionTitleLabel: 'Título do Desafio',
  missionTypeLabel: 'Tipo do Desafio',
  missionLinksLabel: 'Links do Desafio (Opcional, até 3)',

  loadingMissionUpper: 'CARREGANDO DESAFIO...',
  loadingMissionsUpper: 'CARREGANDO DESAFIOS...',
  noGlobalMissionsUpper: 'NENHUM DESAFIO GLOBAL. CRIE UM DESAFIO SEM CAMPANHA PARA COMEÇAR.',
  noCampaignMissionsUpper: 'NENHUM DESAFIO NESTA CAMPANHA. CLIQUE EM "CRIAR DESAFIO" PARA INICIAR.',

  globalMissionsTab: 'Desafios Globais',
  globalMissionsHintUpper: 'DESAFIOS SEM CAMPANHA VINCULADA',
  globalMissionsNotDirect: 'Desafios globais (modelo) não são completados diretamente',
  whoCompletedMission: 'Participantes que já concluíram este desafio',

  createMission: 'Criar Desafio',
  newGlobalMission: 'Novo Desafio Global',
  editMission: 'Editar Desafio',
  globalMissionSuffix: 'Desafio Global',
  campaignMissionSuffix: 'Desafio na Campanha',
  saveMission: 'Salvar Desafio',
  finishAndCreateMission: 'Concluir e Criar Desafio',
  assignMissionToCampaign: 'Atribuir Desafio a uma Campanha',
  confirmDeleteMission: 'Confirmar Exclusão de Desafio',

  missionGoneProse: 'Este desafio não existe mais ou foi removido.',
  missionFormSubtitle: 'Configuração do desafio do participante',
  missionWillBeGlobalProse: 'Este desafio será criado sem campanha vinculada (global).',
  activateMissionNow: 'Ativar desafio imediatamente',
  activeOnlyWhenLinked: 'Ativo/inativo só se aplica quando o desafio está vinculado a uma campanha',
  missionsPageSubtitle: 'Criação e configuração dos desafios dos participantes',
  selectCampaignToManage: 'Selecione a campanha para visualizar e gerenciar seus desafios',
  globalMissionsProse: 'Estes desafios estão prontos mas não estão associados a nenhuma campanha ativa.',
  confirmDeleteProse: 'Tem certeza de que deseja excluir o desafio',
  campaignWipeProse: 'Esta operação apagará todos os dados, desafios, prêmios e cupons associados a esta campanha.',
  reopensMissionsProse: 'participante E reabre os desafios, permitindo ganhar mais cupons',
  reopenMissionsSoonProse: '"Ativa" pra sinalizar que a próxima rodada vem em breve e reabrir os desafios, pra quem quiser',

  referralHintProse: 'Passe esse código pra um amigo cumprir o desafio "Indique um Amigo". Ele ganha cupons na hora; os seus caem quando ele concluir o primeiro desafio dele.',
  receivedCodeProse: 'Recebeu um código de amigo? Vá até o desafio',
  completeMoreProse: 'Quer ganhar ainda mais cupons e aumentar suas chances de ganhar? Complete os desafios disponíveis.',
  campaignFallbackProse: 'Cumpra desafios, junte cupons e concorra a prêmios incríveis!',
  remainingMissionsSubtitle: 'Complete os desafios restantes para ganhar mais cupons!',

  sysReady: 'Pronto',
  sysWaiting: '',

  heroParagraph:
    'Complete os desafios, acumule cupons e aumente suas chances nos sorteios ao vivo. Cada desafio concluído rende novos cupons.',
  ctaRegister: 'Criar minha conta',
  ctaLogin: 'Entrar',

  loginTitle: 'Entrar na sua conta',
  loginSubtitle: 'Acesse com telefone e PIN',
  loginSubmit: 'Entrar',
  loginOverlay: 'Entrando',
  loginNoAccount: 'Ainda não tem conta?',
  loginCreateLink: 'Cadastre-se',

  registerTitle: 'Criar sua conta',
  registerSubtitle: 'Cadastre-se para participar do sorteio',
  registerSubmit: 'Criar conta',
  registerOverlay: 'Criando sua conta',
  registerHasAccount: 'Já tem conta?',

  landingCampaigns: 'Campanhas ativas',
  landingRanking: 'Ranking de cupons',
  landingHowItWorks: 'Como funciona',
  landingFaq: 'Perguntas frequentes',

  step1Title: 'Criar conta',
  step2Title: 'Cumprir desafios',
  step1Desc: 'Cadastre-se com nome, telefone e um PIN de 4 dígitos. Você também informa o código exibido na tela do nosso estande — só quem está no evento consegue criar conta.',
  step2Desc: 'Complete os desafios disponíveis na campanha. Alguns pedem o envio de um comprovante, outros são questionários ou formulários rápidos.',
  step3Title: 'Colete cupons',
  step3Desc: 'Cada desafio concluído adiciona cupons à sua conta. Quanto mais cupons, maiores as suas chances no sorteio.',
  step4Title: 'Acompanhe o sorteio ao vivo',
  step4Desc: 'No horário marcado, acompanhe o sorteio ao vivo pela plataforma e veja os vencedores em tempo real.',

  faq1Q: 'Como funciona o sistema de cupons?',
  faq1A: 'Cada desafio concluído concede uma quantidade de cupons. No momento do sorteio, cada cupom representa uma chance a mais de ser sorteado.',
  faq2Q: 'Que tipos de desafio existem?',
  faq2A: 'Os desafios variam conforme a campanha. Podem incluir envio de comprovantes, quizzes, formulários de feedback ou outras atividades definidas pelos organizadores.',
  faqStandQ: 'Preciso estar no evento para me cadastrar?',
  faqStandA: 'Sim. O cadastro pede um código de 4 dígitos que fica exposto na tela do nosso estande e muda de tempos em tempos. Sem ele não é possível criar conta, e é assim que garantimos que só quem está presente participa do sorteio.',
  faqReferralQ: 'Como funciona o código de amigo?',
  faqReferralA: 'Cada participante tem um código de 6 dígitos. Quem usa o código de um amigo ganha cupons na hora. Já o dono do código só recebe os cupons dele quando a pessoa indicada concluir o primeiro desafio — não basta digitar o código. Cada código vale para até 10 pessoas.',
  faq3A: 'Caso um desafio exija comprovante, siga as instruções na descrição e envie a imagem solicitada. Depois do envio, o desafio é validado conforme as regras da campanha.',

  dashboardLoading: 'Carregando',
  noCampaignProse:
    'Ainda não temos uma campanha ativa. Fique de olho — assim que uma nova campanha começar, ela aparece bem aqui.',
  prizesTitle: 'Prêmios do sorteio',
};

export const copy = THEME === 'cyber' ? cyber : padrao;
