import { THEME } from './current';

const cyber = {
  missions: 'Missões',
  missionsSingular: 'Missão',
  adminMenu: 'Menu Administrativo',
  loading: 'Carregando recursos...',

  backToMissions: 'Voltar para Missões',
  seeMissions: 'Ver Missões',
  seeMyMissions: 'Ver Minhas Missões',
  goToMissions: 'Ir para Missões',
  yourMissions: 'Suas Missões',
  editMissions: 'Editar Missões',
  manageMissionsUpper: 'GERENCIAR MISSÕES',
  missionsCompletedUpper: 'MISSÕES CONCLUÍDAS',
  fulfillMissionsUpper: 'CUMPRIR MISSÕES',
  missionsFrozen: 'Missões congeladas por enquanto',
  missionsFinished: 'Missões encerradas',

  missionDone: 'Missão cumprida',
  missionDoneBang: 'Missão cumprida!',
  missionDoneUpper: 'MISSÃO CUMPRIDA',
  missionNotFound: 'Missão não encontrada',
  unknownMission: 'Missão Desconhecida',

  missionTitleLabel: 'Título da Missão',
  missionTypeLabel: 'Tipo da Missão',
  missionLinksLabel: 'Links da Missão (Opcional, até 3)',

  loadingMissionUpper: 'CARREGANDO MISSÃO...',
  loadingMissionsUpper: 'CARREGANDO MISSÕES...',
  noGlobalMissionsUpper: 'NENHUMA MISSÃO GLOBAL. CRIE UMA MISSÃO SEM CAMPANHA PARA COMEÇAR.',
  noCampaignMissionsUpper: 'NENHUMA MISSÃO NESTA CAMPANHA. CLIQUE EM "CRIAR MISSÃO" PARA INICIAR.',

  globalMissionsTab: 'Missões Globais',
  globalMissionsHintUpper: 'MISSÕES SEM CAMPANHA VINCULADA',
  globalMissionsNotDirect: 'Missões globais (modelo) não são completadas diretamente',
  whoCompletedMission: 'Participantes que já concluíram esta missão',

  createMission: 'Criar Missão',
  newGlobalMission: 'Nova Missão Global',
  editMission: 'Editar Missão',
  globalMissionSuffix: 'Missão Global',
  campaignMissionSuffix: 'Missão na Campanha',
  saveMission: 'Salvar Missão',
  finishAndCreateMission: 'Concluir e Criar Missão',
  assignMissionToCampaign: 'Atribuir Missão a uma Campanha',
  confirmDeleteMission: 'Confirmar Exclusão de Missão',

  missionGoneProse: 'Esta missão não existe mais ou foi removida.',
  missionFormSubtitle: 'Configuração da missão do participante',
  missionWillBeGlobalProse: 'Esta missão será criada sem campanha vinculada (global).',
  activateMissionNow: 'Ativar missão imediatamente',
  activeOnlyWhenLinked: 'Ativo/inativo só se aplica quando a missão está vinculada a uma campanha',
  missionsPageSubtitle: 'Criação e configuração das missões dos participantes',
  selectCampaignToManage: 'Selecione a campanha para visualizar e gerenciar suas missões',
  globalMissionsProse: 'Estas missões estão prontas mas não estão associadas a nenhuma campanha ativa.',
  confirmDeleteProse: 'Tem certeza de que deseja excluir a missão',
  campaignWipeProse: 'Esta operação apagará todos os dados, missões, prêmios e cupons associados a esta campanha.',
  reopensMissionsProse: 'participante E reabre as missões, permitindo ganhar mais cupons',
  reopenMissionsSoonProse: '"Ativa" pra sinalizar que a próxima rodada vem em breve e reabrir as missões, pra quem quiser',

  referralHintProse: 'Passe esse código pra um amigo cumprir a missão "Indique um Amigo" — assim que ele usar, vocês dois ganham cupons na hora.',
  receivedCodeProse: 'Recebeu um código de amigo? Vá até a missão',
  completeMoreProse: 'Quer ganhar ainda mais cupons e aumentar suas chances de ganhar? Complete as missões disponíveis.',
  campaignFallbackProse: 'Cumpra missões, junte cupons e concorra a prêmios incríveis!',
  remainingMissionsSubtitle: 'Complete as missões restantes para ganhar mais cupons!',
};

const feira: typeof cyber = {
  missions: 'Desafios',
  missionsSingular: 'Desafio',
  adminMenu: 'Administração',
  loading: 'Carregando',

  backToMissions: 'Voltar para Desafios',
  seeMissions: 'Ver Desafios',
  seeMyMissions: 'Ver Meus Desafios',
  goToMissions: 'Ir para Desafios',
  yourMissions: 'Seus Desafios',
  editMissions: 'Editar Desafios',
  manageMissionsUpper: 'GERENCIAR DESAFIOS',
  missionsCompletedUpper: 'DESAFIOS CONCLUÍDOS',
  fulfillMissionsUpper: 'CUMPRIR DESAFIOS',
  missionsFrozen: 'Desafios congelados por enquanto',
  missionsFinished: 'Desafios encerrados',

  missionDone: 'Desafio cumprido',
  missionDoneBang: 'Desafio cumprido!',
  missionDoneUpper: 'DESAFIO CUMPRIDO',
  missionNotFound: 'Desafio não encontrado',
  unknownMission: 'Desafio Desconhecido',

  missionTitleLabel: 'Título do Desafio',
  missionTypeLabel: 'Tipo do Desafio',
  missionLinksLabel: 'Links do Desafio (Opcional, até 3)',

  loadingMissionUpper: 'CARREGANDO DESAFIO...',
  loadingMissionsUpper: 'CARREGANDO DESAFIOS...',
  noGlobalMissionsUpper: 'NENHUM DESAFIO GLOBAL. CRIE UM DESAFIO SEM CAMPANHA PARA COMEÇAR.',
  noCampaignMissionsUpper: 'NENHUM DESAFIO NESTA CAMPANHA. CLIQUE EM "CRIAR DESAFIO" PARA INICIAR.',

  globalMissionsTab: 'Desafios Globais',
  globalMissionsHintUpper: 'DESAFIOS SEM CAMPANHA VINCULADA',
  globalMissionsNotDirect: 'Desafios globais (modelo) não são completados diretamente',
  whoCompletedMission: 'Participantes que já concluíram este desafio',

  createMission: 'Criar Desafio',
  newGlobalMission: 'Novo Desafio Global',
  editMission: 'Editar Desafio',
  globalMissionSuffix: 'Desafio Global',
  campaignMissionSuffix: 'Desafio na Campanha',
  saveMission: 'Salvar Desafio',
  finishAndCreateMission: 'Concluir e Criar Desafio',
  assignMissionToCampaign: 'Atribuir Desafio a uma Campanha',
  confirmDeleteMission: 'Confirmar Exclusão de Desafio',

  missionGoneProse: 'Este desafio não existe mais ou foi removido.',
  missionFormSubtitle: 'Configuração do desafio do participante',
  missionWillBeGlobalProse: 'Este desafio será criado sem campanha vinculada (global).',
  activateMissionNow: 'Ativar desafio imediatamente',
  activeOnlyWhenLinked: 'Ativo/inativo só se aplica quando o desafio está vinculado a uma campanha',
  missionsPageSubtitle: 'Criação e configuração dos desafios dos participantes',
  selectCampaignToManage: 'Selecione a campanha para visualizar e gerenciar seus desafios',
  globalMissionsProse: 'Estes desafios estão prontos mas não estão associados a nenhuma campanha ativa.',
  confirmDeleteProse: 'Tem certeza de que deseja excluir o desafio',
  campaignWipeProse: 'Esta operação apagará todos os dados, desafios, prêmios e cupons associados a esta campanha.',
  reopensMissionsProse: 'participante E reabre os desafios, permitindo ganhar mais cupons',
  reopenMissionsSoonProse: '"Ativa" pra sinalizar que a próxima rodada vem em breve e reabrir os desafios, pra quem quiser',

  referralHintProse: 'Passe esse código pra um amigo cumprir o desafio "Indique um Amigo" — assim que ele usar, vocês dois ganham cupons na hora.',
  receivedCodeProse: 'Recebeu um código de amigo? Vá até o desafio',
  completeMoreProse: 'Quer ganhar ainda mais cupons e aumentar suas chances de ganhar? Complete os desafios disponíveis.',
  campaignFallbackProse: 'Cumpra desafios, junte cupons e concorra a prêmios incríveis!',
  remainingMissionsSubtitle: 'Complete os desafios restantes para ganhar mais cupons!',
};

export const copy = THEME === 'cyber' ? cyber : feira;
